config/routes.rb
Rails.application.routes.draw do
  resources :playlists
  resources :channels
  resources :topics
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/javascript", to: 'playlists#javascript'
  get "/deno", to: 'playlists#deno'
  get "/html", to: 'playlists#html'
  get "/python", to: 'playlists#python'
  get "/rails", to: 'playlists#rails'
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :topic
  belongs_to :channel

  # default_scope { order('topic_id,sequence') }  
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
  end

  def deno 
    @playlists = Playlist.where('"playlists"."topic_id" = 5').order('duration ASC')
  end

  def html 
    @playlists = Playlist.where('"playlists"."topic_id" = 2').order('duration ASC')
  end

  def javascript 
    @playlists = Playlist.where('"playlists"."topic_id" = 1 AND "playlists"."completed" = 0').order('sequence ASC')
  end

  def python 
    @playlists = Playlist.where('"playlists"."topic_id" = 3').order('duration ASC')
  end

  def rails 
    @playlists = Playlist.where('"playlists"."topic_id" = 4').order('duration ASC')
  end

  # GET /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def playlist_params
      params.require(:playlist).permit(:topic_id, :channel_id, :title, :url, :total_episode, :finish_episode, :completed, :duration, :image_url, :views, :last_updated, :sequence, :rating)
    end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= form_with(model: playlist, local: true) do |form| %>
  <% if playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
        <% playlist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= form.label :topic_id %>
      <%= form.collection_select :topic_id, Topic.all, :id, :title + :subtitle %>
  </div> 

  <div class="field">
    <%= form.label :channel_id %>
      <%= form.collection_select :channel_id, Channel.order("name ASC"), :id, :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :total_episode %>
    <%= form.number_field :total_episode %>
  </div>

  <div class="field">
    <%= form.label :finish_episode %>
    <%= form.number_field :finish_episode %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :views %>
    <%= form.number_field :views %>
  </div>

  <div class="field">
    <%= form.label :last_updated %>
    <%= form.date_select :last_updated %>
  </div>

  <div class="field">
    <%= form.label :sequence %>
    <%= form.number_field :sequence %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/playlists/_playlist.html.erb
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">

    <div class="card mb-4">

        <%= link_to playlist do %> 

            <%= image_tag src="https://i.ytimg.com/vi/"+playlist.image_url+"/mqdefault.jpg",
                class: "card-img-top img-fluid" %> 

        <% end %>

        <div class="card-block">       

            <div class="card-body">

                <p class="card-text">

                    <span style="float: left;">

                        <%= image_tag playlist.channel.image, width: 30 %>  

                        <%= link_to playlist.channel.name,
                            "https://www.youtube.com/channel/"+playlist.channel.url, 
                            target: "_new"
                        %>

                    </span>

                    <span style="float: right;">

                        <%= number_to_human(playlist.channel.subscriber, :format => '%n%u',
                            :precision => 2, 
                            :units => { :thousand => 'K', :million => 'M', :billion => 'B'}) %>

                    </span>

                </p>

                <p class="card-text" style="clear: both;">

                    <span style="float: left;">

                        <%= "Videos: " + playlist.total_episode.to_s %>

                    </span>

                    <span style="float: right;">

                        <%= "Views: " + number_to_human(playlist.views, :format =>
                        '%n%u', :precision => 2, 
                        :units => { :thousand => 'K', :million => 'M', :billion => 'B' }) %>

                    </span>

                </p>

                <p class="card-text" style="clear: both;">

                    <span style="float: left;">

                        <%= "Duration: " + seconds_to_human(playlist.duration).to_s %>

                    </span>

                    <%# <span style="float: right;">

                        <%= playlist.last_updated.strftime("%Y/%m") 

                    </span> %>

                </p>

                <div style="clear: both;">

                    <% if (playlist.total_episode > 1) %> 

                        <%= link_to 'View',
                        "https://www.youtube.com/playlist?list="+playlist.url, target: "_new",
                        :class => "btn btn-success btn-block" %> 

                    <% else %> 

                        <%= link_to 'View',
                        "https://youtu.be/"+playlist.url, target: "_new", class: "btn
                        btn-success btn-block" %> 

                    <% end %>

                </div>

            </div>
            <!-- End of Card Body -->

        </div>
        <!-- End of Card Block -->    

    </div>
    <!-- End of Card -->

</div>
<!-- End of Column -->

app/views/playlists/deno.html.erb
<% provide(:page_title, 'Deno') %> 
<% provide(:deno_active, 'active') %>

<!-- Begin of Copy & Paste -->
<div class="row">
  <%= render @playlists %>
</div>
<!-- End of Copy & Paste -->

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/html.html.erb
<% provide(:page_title, 'HTML') %>
<% provide(:html_active, 'active') %>

<!-- Begin of Copy & Paste -->
<div class="row">

  	<%= render @playlists %>

</div> 
<!-- End of Copy & Paste -->

app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>
<% provide(:page_title, 'Playlists') %> 
<% provide(:playlist_active, 'active') %>

<h1>Playlists</h1>
<%= link_to 'New Playlist', new_playlist_path %>

<table id="playlists" class="table table-striped">
  <thead>
    <tr>
      <th>Topic</th>
      <th>Channel</th>
      <th>Title</th>
      <th>Total episode</th>
      <th>Finish episode</th>
      <th>Completed</th>
      <th>Duration</th>
      <th>Views</th>
      <th>Last updated</th>
      <th>Sequence</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.topic.title %></td>
        <td><%= playlist.channel.name %></td>
        <td><%= playlist.title %></td>
        <td><%= playlist.total_episode %></td>
        <td><%= playlist.finish_episode %></td>
        <td><%= playlist.completed %></td>
        <td><%= seconds_to_hour(playlist.duration) %></td>
        <td><%= number_to_human(playlist.views, :format => '%n%u', :precision => 2, :units => { :thousand => 'K', :million => 'M', :billion => 'B' }) %></td>
        <td><%= playlist.last_updated %></td>
        <td><%= playlist.sequence %></td>
        <td><%= playlist.rating %></td>
        <td><%= link_to 'S', playlist %></td>
        <td><%= link_to 'E', edit_playlist_path(playlist) %></td>
        <td><%= link_to 'D', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlist', new_playlist_path %>

app/views/playlists/javascript.html.erb
<% provide(:page_title, 'JavaScript') %>
<% provide(:react_active, 'active') %>

<!-- Begin of Copy & Paste -->
<div class="row">

  	<%= render @playlists %>

</div> 
<!-- End of Copy & Paste -->

app/views/playlists/new.html.erb
<% provide(:page_title, 'New Playlist') %> <% provide(:playlists_active, 'active') %>

<h1>New Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/python.html.erb
<% provide(:page_title, 'Python') %> <% provide(:python_active, 'active') %>

<!-- Begin of Copy & Paste -->
<div class="row">
  <%= render @playlists %>
</div>
<!-- End of Copy & Paste -->

app/views/playlists/rails.html.erb
<% provide(:page_title, 'Rails') %> 
<% provide(:rails_active, 'active') %>

<!-- Begin of Copy & Paste -->
<div class="row">
  <%= render @playlists %>
</div>
<!-- End of Copy & Paste -->

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>
<% provide(:page_title, 'Show Playlist') %>
<% provide(:playlist_active, 'active') %>

<div class="page-header text-center" >
<% if @playlist.total_episode > 1 %>
<%= link_to 'View', "https://www.youtube.com/playlist?list="+@playlist.url, target: "_new",
  :class => "btn btn-success pull-right"  %>
  <% else %>
<%= link_to 'View', "https://youtu.be/"+@playlist.url, target: "_new",
  :class => "btn btn-success pull-right"  %>  
  <% end %>
</div>

<p>
  <strong>Topic:</strong>
  <%= @playlist.topic_id %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @playlist.channel_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @playlist.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= link_to(@playlist.url, "https://www.youtube.com/playlist?list="+@playlist.url, target: "_new") %>
</p>

<p>

    <%= link_to @playlist do %> 
      <%= image_tag src="https://i.ytimg.com/vi/"+@playlist.image_url+"/mqdefault.jpg", width: 100 %> 
    <% end %>
      
</p>

<p>
  <strong>Total episode:</strong>
  <%= @playlist.total_episode %>
</p>

<p>
  <strong>Finish episode:</strong>
  <%= @playlist.finish_episode %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @playlist.completed %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @playlist.duration %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @playlist.image_url %>
</p>

<p>
  <strong>Views:</strong>
  <%= @playlist.views %>
</p>

<p>
  <strong>Last updated:</strong>
  <%= @playlist.last_updated %>
</p>

<p>
  <strong>Sequence:</strong>
  <%= @playlist.sequence %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @playlist.rating %>
</p>

<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>