config/routes.rb
Rails.application.routes.draw do
  resources :playlists
  resources :channels
  resources :topics
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/javascript", to: 'playlists#javascript'
  get "/deno", to: 'playlists#deno'
  get "/html", to: 'playlists#html'
  get "/python", to: 'playlists#python'
  get "/rails", to: 'playlists#rails'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-faded">

    <a class="navbar-brand" href="#">Navbar</a>

    <button 
        class="navbar-toggler pull-xs-right"
        type="button" 
        data-toggle="collapse" 
        data-target="#navbarMenu" 
    >

    <span class="navbar-toggler-icon"></span>
    
  </button>

  <div class="collapse navbar-collapse" id="navbarMenu">

    <ul class="navbar-nav ml-auto">

      <li class="nav-item">

          <%= link_to "Home", root_path, 
          class: "nav-link" %>

      </li>

	    <li>

          <%= link_to 'Deno', deno_path, 
            class: "nav-link #{yield(:deno_active)}" %>

      </li> 

	    <li>

          <%= link_to 'HTML', html_path, 
            class: "nav-link #{yield(:html_active)}" %>

      </li> 

	    <li>

          <%= link_to 'JavaScript', javascript_path, 
            class: "nav-link #{yield(:javascript_active)}" %>

      </li> 

	    <li>

          <%= link_to 'Python', python_path, 
            class: "nav-link #{yield(:python_active)}" %>

      </li> 

	    <li>

      <li>

          <%= link_to 'Rails', rails_path, 
            class: "nav-link #{yield(:rails_active)}" %>

      </li> 

      <li>

          <%= link_to "Playlists", playlists_path, 
              class: "nav-link #{yield(:playlist_active)}" %>

      </li>    

      <li>

        <%= link_to "Channels", channels_path, 
            class: "nav-link #{yield(:channel_active)}" %>

      </li>       

      <li class="nav-item">

        <%= link_to "Topics", topics_path, 
            class: "nav-link #{yield(:topic_active)}" %>

      </li>   

    </ul>
    
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<title><%= yield(:page_title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" 
    crossorigin="anonymous"> %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container <%= controller_name %> <%= action_name %>">

      <%= render 'layouts/navbar' %>

      <%= yield %>

    </div>

  </body>
</html>



    